### PR TITLE
v0.6 (New APIs)

### LINKED ISSUE #7: Mediation networks
Hello, 
At last a no ad sharing admob plugin. great job!
Does it support mediation for iAd, FacebookAds for instance?
How difficult would it be to implement that?
I'm willing to have a look into it but need some hints.
Thank you

### LINKED ISSUE #38: [RFC] Better events
I am working on next release to provide better API usage, one area to fix the emitted events.
I would like to hear some feedback for the following proposals before proceed,

#### 1. Generic events between different ad-types. E.g. `AdLoaded`, `AdFailed` events with `adType` in the event data.

**Pros**
- Less event types
- Some generic handling function, only need to listen to one event type. E.g. log `AdFailed`

**Cons**
- Some ad-types may emit more or less events. E.g. `AdRewarded` is only used by rewarded video
- Some ad-types event data may contain extra information, which can be hard to consume as `adType` need to be checked.

#### 2. Each ad-type has its own set of events. E.g, `BannerLoaded`, `InterstitialFailed` events.

**Pros**
- No need to check `adType` in the handling function

**Cons**
- Increase the number of events

I prefer (2) as it is more explicit, what do you think? @becvert @vintage @code4youreal @warcry2000
Maybe you have better idea.

### PR DESCRIPTION
**Pull request by ratson**
This release includes reward video support, new set of APIs and emit events with namespace.

Before releasing it, I would like to make sure it is fully backward-compatible, so people could upgrade smoothly.

@vintage @warcry2000 @becvert @code4youreal Would you try this out and let me know if it breaks your code?

Close #7, #16, #37, #38, #39, #41.

### CODE REVIEW

**Comment by warcry2000** [comment]
Hi, I have not been able to try these days. Between today and tomorrow I try to do the tests.
Thanks

**Comment by ratson** [comment]
Never mind, I am still polishing the docs, let me know if you find anything is not clear.

**Comment by warcry2000** [comment]
@ratson I installed the plugin:
when I do:
 cordova build android
Give me the following error:

Error: cmd: Command failed with exit code 1 Error output....
android\src\name\ratson\cordova\admob\banner\BannerListener.java:52: error: cannot find symbol
executor.fireadevent("admob.banner.event.LOAD", data);
symbol: variable data
location: class BannerListener

regards

**Comment by swaraasolutions** [comment]
Any ideas when you are merging this pull request ios is not working currently and not showing any banner google works fine though i have been using phonegap build and keep on getting errors related to sdk about deprecated function for init etc.

**Comment by ratson** [comment]
@warcry2000 Fixed the error

@swaraasolutions Would you paste the error for reference? Some deprecated functions may still be using by cordova / phonegap for backward compatibility.

**Comment by swaraasolutions** [comment]
Sure i can paste the error in sometime also does it make any difference if i am using Ionic?

**Comment by warcry2000** [comment]
@ratson In android, without touching any code, my application works correctly, both banner and interstitial
In IOS I try tomorrow.

¿Do you have an example of how to use the new api? To go testing too.

**Comment by ratson** [comment]
The example is updated to use new APIs, you can browse it at https://github.com/ratson/cordova-plugin-admob-free/blob/next/example/www/js/index.js

**Comment by warcry2000** [comment]
@ratson In IOS, without touching any code, my application works correctly, both banner and interstitial.

Now I will modify the code with the new api, with banner, interstitial and video, I prove it and I will report the conclusions.

**Comment by warcry2000** [comment]
@ratson 
The tests carried out with the New API are:
Android:
- Banner: ok
- Interstitial: ko. Black Screen, although it says it is created correctly,  but you see a black screen.
- Video: ok
- Events: ok

IOS:
- Banner: ok
- Interstitial: ok
- Video: ko. I'm trying to see what happens.
- Events: ok,  although I have not tried video.
Anyway in ios, npm install did not work for me, and I copied that of android. I do not know if this has had to do with the error of the video.

**Comment by Script47** [comment]
Is this safe to use? Meaning has it been tested?

**Comment by becvert** [comment]
It's good to me.
I'm only using interstitials though.
Thanks

**Pull request merged**
