### PR TITLE
fix: Make plugin available for Ads SDK v17.0.0

### LINKED ISSUE #286: Not working with play-services-ads v17.0.0
Google published version 17 of play-services-ads. To make it working with it, the plugin has to add a new requirement for a `<meta-data>` tag in AndroidManifest.xml:

`Google AdMob publishers are required to specify a <meta-data> tag with key com.google.android.gms.ads.APPLICATION_ID. See the AdMob getting started guide for more details.`

Source: https://developers.google.com/android/guides/releases#october_5th_2018

### PR DESCRIPTION
**Pull request by paulstelzer**
fix #286

- Add a new preference (ADMOB_APP_ID - like mentioned in https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml)

- Update the android-manifest.xml by using the preference

### CODE REVIEW

**Comment by gnarvaja** [comment]
"com.google.android.gms.ads.AD_MANAGER_APP" isn't required too?

https://developers.google.com/ad-manager/mobile-ads-sdk/android/quick-start

**Comment by paulstelzer** [comment]
This is only required if it's an Ad Manager app - I don't think that anyone is using Google Ad Manager :D I think tey are using Admob

**Comment by gnarvaja** [comment]
Yes, sorry, my mistake. I read it again and it's one setting or the other, depending if you use admob or ad manager.

+1 for this PR

**Comment by mm44** [comment]
Hi,
About initializing MobileAds (MobileAds.initialize) : 
Is it required ? Does the last version of the plugin supports it ?

**Pull request merged**
